# Generated by Django 5.1.7 on 2025-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Biography', 'Biography')], max_length=50)),
                ('first_published', models.DateField(auto_now_add=True)),
                ('last_published', models.DateField(auto_now=True)),
            ],
        ),
    ]
