# Generated by Django 5.1.4 on 2025-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='first_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='last_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
