# Generated by Django 5.1.4 on 2025-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('roll', models.IntegerField(unique=True, verbose_name='ID number')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('city', models.CharField(max_length=50, verbose_name='City Name')),
            ],
        ),
    ]
