# Generated by Django 5.1.4 on 2025-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
