# Generated by Django 5.2.5 on 2025-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_by',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
